version: "3.8"

services:
  database:
    image: postgres:15.6
    container_name: rolesDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roles
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgres/data